/* eslint-disable react/no-unescaped-entities */
import {
  COMPANY_NAME,
  DELETE_ACCOUNT,
  EMAIL,
  LOGIN_PROVIDERS,
  SITE,
} from "@/app/legal/legal-config";

const Page = () => {
  return (
    <div className="container prose py-12 dark:prose-invert">
      <h1>Privacy Policy</h1>
      <h2>Introduction</h2>
      <p>
        {COMPANY_NAME} ("us", "we", or "our") operates {SITE} (hereinafter
        referred to as "Service").
      </p>
      <p>
        Our Privacy Policy governs your visit to {SITE} , and explains how we
        collect, safeguard and disclose information that results from your use
        of our Service.
      </p>
      <p>
        We use your data to provide and improve Service. By using Service, you
        agree to the collection and use of information in accordance with this
        policy. Unless otherwise defined in this Privacy Policy, the terms used
        in this Privacy Policy have the same meanings as in our Terms and
        Conditions.
      </p>
      <p>
        Our Terms and Conditions ("Terms") govern all use of our Service and
        together with the Privacy Policy constitutes your agreement with us
        ("agreement").
      </p>
      <p>
        You can delete your account at any time by logging into your account and
        visiting <a href={DELETE_ACCOUNT}>{DELETE_ACCOUNT}</a>. If that is not
        possible, please contact us at {EMAIL}
      </p>
      <h2>Definitions</h2>
      <p>SERVICE means the {SITE} website</p>
      <p>
        PERSONAL DATA means data about a living individual who can be identified
        from those data (or from those and other information either in our
        possession or likely to come into our possession).
      </p>
      <p>
        USAGE DATA is data collected automatically either generated by the use
        of Service or from Service infrastructure itself (for example, the
        duration of a page visit).
      </p>
      <p>
        COOKIES are small files stored on your device (computer or mobile
        device).
      </p>
      <p>
        DATA CONTROLLER means a natural or legal person who (either alone or
        jointly or in common with other persons) determines the purposes for
        which and the manner in which any personal data are, or are to be,
        processed. For the purpose of this Privacy Policy, we are a Data
        Controller of your data.
      </p>
      <p>
        DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal person
        who processes the data on behalf of the Data Controller. We may use the
        services of various Service Providers in order to process your data more
        effectively.
      </p>
      <p>
        DATA SUBJECT is any living individual who is the subject of Personal
        Data.
      </p>
      <p>
        THE USER is the individual using our Service. The User corresponds to
        the Data Subject, who is the subject of Personal Data.
      </p>
      <h2>Types of Data Collected</h2>
      <p>We collect personal information that you provide to us.</p>
      <p>
        We collect personal information that you voluntarily provide to us when
        you register on the Services, express an interest in obtaining
        information about us or our products and Services, when you participate
        in activities on the Services, or otherwise when you contact us.
      </p>
      <p>
        The personal information we collect may include the following: email
        addresses, usernames, names, profile picture.
      </p>
      <p>
        You have the ability to register and log in using own of the following,
        but not limited to, third-party login providers:
        <ul>
          {LOGIN_PROVIDERS.map((provider) => (
            <li key={provider}>{provider}</li>
          ))}
        </ul>
      </p>
      <p>
        The profile information we receive may vary depending on the login
        provider concerned, but will often include your name, email address, and
        profile picture, as well as other information you choose to make public.
      </p>

      <h2>Transfer of Data</h2>
      <p>
        Your information, including Personal Data, may be transferred to -- and
        maintained on -- computers located outside of your state, province,
        country or other governmental jurisdiction where the data protection
        laws may differ from those of your jurisdiction.
      </p>
      <p>
        If you are located outside United States and choose to provide
        information to us, please note that we transfer the data, including
        Personal Data, to United States and process it there.
      </p>
      <p>
        Your consent to this Privacy Policy followed by your submission of such
        information represents your agreement to that transfer.
      </p>
      <p>
        We will take all the steps reasonably necessary to ensure that your data
        is treated securely and in accordance with this Privacy Policy and no
        transfer of your Personal Data will take place to an organisation or a
        country unless there are adequate controls in place including the
        security of your data and other personal information.
      </p>
      <h2>Security of Data</h2>
      <p>
        The security of your data is important to us but remember that no method
        of transmission over the Internet or method of electronic storage is
        100% secure. While we strive to use commercially acceptable means to
        protect your Personal Data, we cannot guarantee its absolute security.
      </p>
      <h3>GDPR</h3>
      <p>
        If you are a resident of the European Union (EU) and European Economic
        Area (EEA), you have certain data protection rights, covered by GDPR. --
        See more at https://eur-lex.europa.eu/eli/reg/2016/679/oj
      </p>
      <p>
        We aim to take reasonable steps to allow you to correct, amend, delete,
        or limit the use of your Personal Data.
      </p>
      <p>
        If you wish to be informed what Personal Data we hold about you and if
        you want it to be removed from our systems, please email us at {EMAIL}.
      </p>
      <p>
        In certain circumstances, you have the following data protection rights:
      </p>
      <p>
        a. the right to access, update or to delete the information we have on
        you;
      </p>
      <p>
        b. the right of rectification. You have the right to have your
        information rectified if that information is inaccurate or incomplete;
      </p>
      <p>
        c. the right to object. You have the right to object to our processing
        of your Personal Data;
      </p>
      <p>
        d. the right of restriction. You have the right to request that we
        restrict the processing of your personal information;
      </p>
      <p>
        e. the right to data portability. You have the right to be provided with
        a copy of your Personal Data in a structured, machine-readable and
        commonly used format;
      </p>
      <p>
        f. the right to withdraw consent. You also have the right to withdraw
        your consent at any time where we rely on your consent to process your
        personal information;
      </p>
      <p>
        Please note that we may ask you to verify your identity before
        responding to such requests. Please note, we may not able to provide
        Service without some necessary data.
      </p>
      <p>
        You have the right to complain to a Data Protection Authority about our
        collection and use of your Personal Data. For more information, please
        contact your local data protection authority in the European Economic
        Area (EEA).
      </p>

      <h3>CCPA</h3>
      <p>
        This section applies only to California residents. Under the California
        Consumer Privacy Act (CCPA), you have the rights listed below.
      </p>
      <p>
        The California Code of Regulations defines a "residents" as: (1) every
        individual who is in the State of California for other than a temporary
        or transitory purpose and (2) every individual who is domiciled in the
        State of California who is outside the State of California for a
        temporary or transitory purpose. All other individuals are defined as
        "non-residents."
      </p>
      <p>
        If this definition of "resident" applies to you, we must adhere to
        certain rights and obligations regarding your personal information.
      </p>
      <p>Your rights with respect to your personal data:</p>
      <ul>
        <li>Right to request deletion of the data — Request to delete.</li>
        <li>
          Right to be informed — Request to know. Depending on the
          circumstances, you have a right to know: whether we collect and use
          your personal information; the categories of personal information that
          we collect; the purposes for which the collected personal information
          is used; whether we sell or share personal information to third
          parties; the categories of personal information that we sold, shared,
          or disclosed for a business purpose; the categories of third parties
          to whom the personal information was sold, shared, or disclosed for a
          business purpose; the business or commercial purpose for collecting,
          selling, or sharing personal information; and the specific pieces of
          personal information we collected about you.
        </li>
        <li>
          Right to Non-Discrimination for the Exercise of a Consumer’s Privacy
          Rights. We will not discriminate against you if you exercise your
          privacy rights.
        </li>
        <li>
          Right to Limit Use and Disclosure of Sensitive Personal Information.
          We do not process consumer's sensitive personal information.
        </li>
      </ul>
      <p>
        Verification process: Upon receiving your request, we will need to
        verify your identity to determine you are the same person about whom we
        have the information in our system. We will only use personal
        information provided in your request to verify your identity or
        authority to make the request. To the extent possible, we will avoid
        requesting additional information from you for the purposes of
        verification. However, if we cannot verify your identity from the
        information already maintained by us, we may request that you provide
        additional information for the purposes of verifying your identity and
        for security or fraud-prevention purposes. We will delete such
        additionally provided information as soon as we finish verifying you.
      </p>
      <p>
        Other privacy rights: You may object to the processing of your personal
        information. You may request correction of your personal data if it is
        incorrect or no longer relevant, or ask to restrict the processing of
        the information. You can designate an authorized agent to make a request
        under the CCPA on your behalf. We may deny a request from an authorized
        agent that does not submit proof that they have been validly authorized
        to act on your behalf in accordance with the CCPA. You may request to
        opt out from future selling or sharing of your personal information to
        third parties. Upon receiving an opt-out request, we will act upon the
        request as soon as feasibly possible, but no later than fifteen (15)
        days from the date of the request submission.
      </p>

      <h2>Cookies</h2>
      <p>
        Our website uses HTTP cookies to store user-specific data. We only use
        first party cookies for the user session.
      </p>
      <h2>Service Providers</h2>
      <p>
        We may employ third party companies and individuals to facilitate our
        Service ("Service Providers"), provide Service on our behalf, perform
        Service-related services or assist us in analysing how our Service is
        used.
      </p>

      <p>
        These third parties have access to your Personal Data only to perform
        these tasks on our behalf and are obligated not to disclose or use it
        for any other purpose.
      </p>

      <h2>Children’s Privacy</h2>

      <p>
        Our Services are not intended for use by children under the age of 18
        ("Child" or "Children").
      </p>

      <p>
        We do not knowingly collect personally identifiable information from
        Children under 18. If you become aware that a Child has provided us with
        Personal Data, please contact us. If we become aware that we have
        collected Personal Data from Children without verification of parental
        consent, we take steps to remove that information from our servers.
      </p>

      <h2>Communication and Marketing</h2>
      <p>
        By using our Service and authenticating through Discord or Google, you
        provide us with your email address. We may use this to communicate with
        you about:
      </p>
      <ul>
        <li>Your account and important service updates</li>
        <li>New features or changes to our services</li>
        <li>Marketing information about our services</li>
        <li>Other services or events we think may interest you</li>
      </ul>
      <p>
        We use your contact information to provide, maintain, and improve our
        Service, as well as to send you relevant information and marketing
        communications.
      </p>
      <p>
        You can opt out of marketing communications at any time by clicking the
        "unsubscribe" link in our emails or by contacting us at {EMAIL}. You'll
        still receive essential service-related messages even if you opt out of
        marketing communications.
      </p>

      <h2>Changes to This Privacy Policy</h2>

      <p>
        We may update our Privacy Policy from time to time. We will notify you
        of any changes by posting the new Privacy Policy on this page. Please
        check this page again for any changes to our Privacy Policy.
      </p>

      <h2>Contact</h2>
      <p>If you have questions or comments, you may email us at {EMAIL}</p>

      <h2>Analytics</h2>
      <p>
        We use a privacy-friendly analytics tool to improve the usage of our
        website. This tool works without cookies and does not store any personal
        data.
      </p>

      <p>The following information, among others, is collected:</p>
      <ul>
        <li>Page views</li>
        <li>Referrers</li>
        <li>Device type</li>
        <li>Browser</li>
        <li>Approximate location (country)</li>
      </ul>

      <h2>Sponsored Links</h2>
      <p>
        We may include sponsored links or affiliate content on our website.
        These are links to products, services, or websites of third parties that
        may compensate us for traffic or sales generated from referrals.
      </p>

      <p>
        For information about data we collect related to site usage, including
        interactions with sponsored content, please refer to our Analytics
        section.
      </p>

      <h3>Third-Party Websites</h3>
      <p>
        Sponsored links will direct you to third-party websites. Please note:
      </p>
      <ul>
        <li>
          These websites have their own privacy policies and terms of service.
        </li>
        <li>
          We are not responsible for the privacy practices of these third-party
          sites.
        </li>
        <li>
          We encourage you to read the privacy policies of any third-party sites
          you visit.
        </li>
      </ul>

      <h3>Transparency</h3>
      <p>
        All sponsored content and affiliate links on our site are clearly
        labeled as "Sponsored" to ensure transparency.
      </p>

      <h3>Your Choice</h3>
      <p>
        You have the choice not to click on sponsored links. Your use of our
        service will not be affected if you choose not to interact with
        sponsored content.
      </p>

      <h3>Data Collection</h3>
      <p>
        We may collect non-personally identifiable data about interactions with
        sponsored links for internal analytics and to fulfill our obligations to
        sponsors. This data is always aggregated and anonymized.
      </p>
    </div>
  );
};

export default Page;
